[WIP] RATY-116 vulnerable dependencies
City-of-Helsinki/pysakoinnin-sahk-asiointi-ui pull request #153
Opened 2024-05-29 10:55 UTC by mikkojamG

2024-05-29 11:35 UTC, terovirtanen commented
**PYSAKOINNIN-SAHK-ASIOINTI-UI branch is deployed to platta: https://pysakoinnin-sahk-asiointi-pr153-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-29 11:53 UTC, terovirtanen commented
**PYSAKOINNIN-SAHK-ASIOINTI-UI branch is deployed to platta: https://pysakoinnin-sahk-asiointi-pr153-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-29 12:57 UTC, terovirtanen commented
**PYSAKOINNIN-SAHK-ASIOINTI-UI branch is deployed to platta: https://pysakoinnin-sahk-asiointi-pr153-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-30 05:43 UTC, terovirtanen commented
**PYSAKOINNIN-SAHK-ASIOINTI-UI branch is deployed to platta: https://pysakoinnin-sahk-asiointi-pr153-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-06-07 11:21 UTC, arpargo requested changes

2024-06-07 11:25 UTC, terovirtanen commented
**PYSAKOINNIN-SAHK-ASIOINTI-UI branch is deployed to platta: https://pysakoinnin-sahk-asiointi-pr153-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-06-10 07:50 UTC, terovirtanen commented
**PYSAKOINNIN-SAHK-ASIOINTI-UI branch is deployed to platta: https://pysakoinnin-sahk-asiointi-pr153-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-06-10 07:50 UTC, mikkojamG commented on .env.test
[154a929](https://github.com/City-of-Helsinki/pysakoinnin-sahk-asiointi-ui/pull/153/commits/154a929f3d18512b0b3bbc138723ac422443f3b1)

2024-06-10 09:44 UTC, arpargo approved these changes
LGTM

2024-06-10 09:47 UTC, merged