HDS Login
City-of-Helsinki/pysakoinnin-sahk-asiointi-ui pull request #169
Opened 2024-10-31 17:55 UTC by voneiden

2024-11-04 10:45 UTC, mikkojamG requested changes

2024-11-04 10:45 UTC, mikkojamG commented on src/pages/Index.tsx
> +  useApiTokens();
This does not seem to be used for anything 🤔

2024-11-04 19:49 UTC, voneiden commented on src/components/Header.tsx
> +  useOidcClientTracking();
This one's actually really important for ensuring that  `WithAuthentication` gets re-rendered when user changes. `useOidcClientTracking()` forces component re-rendering when user is 

- USER_UPDATED
- USER_REMOVED
- USER_RENEWAL_STARTED

But I will still revisit the usage as there's the second WithAuthentication.

2024-11-04 20:30 UTC, voneiden commented on src/App.tsx
> +import { AuthError } from './pages/authError';
It seems I had a few small commits I failed to push :sob:

2024-11-04 20:32 UTC, voneiden commented on src/components/Header.tsx
> +  useOidcClientTracking();
useOidcClientTracking(); is now used in three places. There was also the <ProtectedRoute> that I missed earlier.

2024-11-04 20:32 UTC, voneiden commented
I originally thought I need  `useApiTokens` with `useGraphQL`, but it seems everything works now fine with just OidcClientTracking.

2024-11-05 06:21 UTC, mikkojamG requested changes

2024-11-05 06:21 UTC, mikkojamG commented on src/components/PageContainer.tsx
> +//import ErrorPrompt from './ErrorPrompt';
Unused import here 👀

2024-11-05 10:57 UTC, mikkojamG approved these changes
LGTM (besides FileInput bug) 👀

2024-12-02 11:04 UTC, terovirtanen commented
**PYSAKOINNIN-SAHK-ASIOINTI-UI branch is deployed to platta: https://pysakoinnin-sahk-asiointi-pr169-ui.dev.hel.ninja** :rocket::rocket::rocket:

2024-12-02 11:06 UTC, terovirtanen commented
## e2e tests result is __success__ for https://pysakoinnin-sahk-asiointi-pr169-ui.dev.hel.ninja :laughing::tada::tada::tada:

2024-12-02 12:06 UTC, merged